/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import com.core.exceptions.math.IntegerBeyondLimitException;
import com.core.utils.math.BasicOperations;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testAddPositive() throws IntegerBeyondLimitException {
        BasicOperations classUnderTest = new BasicOperations();
        System.out.println("Testing....");
        assertEquals(0, classUnderTest.add(-10,20));
    }
}
